### ISSUE TITLE
Insert array list as edge property in HgraphDB

### ISSUE THREAD

**Issue by niloo-sh** [rayokota/hgraphdb#41]
Hi,
I insert an array list as the edge property with [(String,String),(String,String),...] format.
but when the size of this array increases, I get this error:

` java.lang.ArrayIndexOutOfBoundsException: 4096`

Is there any limitation?

**Comment by rayokota** [comment]
Can you provide the complete stack trace?

**Comment by niloo-sh** [comment]
I read data from kafka through Flink and insert them to HGraphDB, if the edge is repeated it's start and end time(as ZonedDateTime which converted to string) add to edge property as a tuple2<String,String>.
In my code, each string has 19 characters and when Array List size is reached to 38 I get following exception:
```
Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$7.apply$mcV$sp(JobManager.scala:933)
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$7.apply(JobManager.scala:876)
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$7.apply(JobManager.scala:876)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Exception occurred while processing valve output watermark: 
	at org.apache.flink.streaming.runtime.io.StreamInputProcessor$ForwardingValveOutputHandler.handleWatermark(StreamInputProcessor.java:289)
	at org.apache.flink.streaming.runtime.streamstatus.StatusWatermarkValve.findAndOutputNewMinWatermarkAcrossAlignedChannels(StatusWatermarkValve.java:173)
	at org.apache.flink.streaming.runtime.streamstatus.StatusWatermarkValve.inputWatermark(StatusWatermarkValve.java:108)
	at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:188)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:69)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:263)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:702)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:530)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:503)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:483)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:891)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:869)
	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51)
	at org.apache.flink.streaming.api.functions.windowing.PassThroughWindowFunction.apply(PassThroughWindowFunction.java:35)
	at org.apache.flink.streaming.runtime.operators.windowing.functions.InternalSingleValueWindowFunction.process(InternalSingleValueWindowFunction.java:44)
	at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.emitWindowContents(WindowOperator.java:597)
	at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.onEventTime(WindowOperator.java:504)
	at org.apache.flink.streaming.api.operators.HeapInternalTimerService.advanceWatermark(HeapInternalTimerService.java:275)
	at org.apache.flink.streaming.api.operators.InternalTimeServiceManager.advanceWatermark(InternalTimeServiceManager.java:107)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.processWatermark(AbstractStreamOperator.java:946)
	at org.apache.flink.streaming.runtime.io.StreamInputProcessor$ForwardingValveOutputHandler.handleWatermark(StreamInputProcessor.java:286)
	... 7 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4096
	at org.apache.hadoop.hbase.util.SimplePositionedMutableByteRange.put(SimplePositionedMutableByteRange.java:213)
	at org.apache.hadoop.hbase.util.SimplePositionedMutableByteRange.put(SimplePositionedMutableByteRange.java:179)
	at org.apache.hadoop.hbase.util.OrderedBytes.encodeBlobVar(OrderedBytes.java:1055)
	at org.apache.hadoop.hbase.util.OrderedBytes.encodeBlobVar(OrderedBytes.java:1081)
	at io.hgraphdb.ValueUtils.serialize(ValueUtils.java:258)
	at io.hgraphdb.ValueUtils.serialize(ValueUtils.java:176)
	at io.hgraphdb.ValueUtils.serializePropertyValue(ValueUtils.java:171)
	at io.hgraphdb.mutators.PropertyWriter.constructMutations(PropertyWriter.java:31)
	at io.hgraphdb.mutators.Mutators.write(Mutators.java:60)
	at io.hgraphdb.HBaseElement.setProperty(HBaseElement.java:182)
	at io.hgraphdb.HBaseEdge.property(HBaseEdge.java:133)
	at com.asha.adw.ga.dle.dataloading.HGraphDBInserter.insertMultiPropertyToHGraphDB(HGraphDBInserter.java:341)
	at com.asha.adw.ga.dle.dataloading.HGraphDBInserter$InsertMultiPropertyEdgeToGragh.map(HGraphDBInserter.java:158)
	at com.asha.adw.ga.dle.dataloading.HGraphDBInserter$InsertMultiPropertyEdgeToGragh.map(HGraphDBInserter.java:154)
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:41)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:528)
	... 20 more

```

**Comment by rayokota** [comment]
Ok, I will look at making the maximum size configurable.

**Comment by niloo-sh** [comment]
Looking forward to hearing from you.
Thanks

**Comment by rayokota** [comment]
This is fixed.  Please upgrade to 1.0.4.  No configuration changes are necessary.

**Comment by niloo-sh** [comment]
It works correctly. 
Thanks a lot.
