### ISSUE TITLE
Creating too many threads to hbase 

### ISSUE THREAD

**Issue by ronaldFeri** [rayokota/hgraphdb#42]
I created a connection from Flink to HgraphDB and load graph data to be processed by Flink Gelly algorithms. But I faced a strange problem when loading data and running algorithms: memory consumption increasingly goes up even after completing jobs. I monitored the heap and realized that there are many connections threads to HgraphDB and even they go up over time. Here is a sample thread name: 

_"hconnection-0x342a5ef0-shared--pool1-t1353"_

All new threads are suspended. I make connection as follow: 

   _HBaseGraphConfiguration hconf = HGraphDBConfiguration.createHGraphDBConfig(props);
        ExecutionEnvironment env = ExecutionEnvironment.getExecutionEnvironment();
        DataSet<Tuple3<String, String, Integer>> edges = env.createInput(
                new HBaseEdgeInputFormat<>(hconf, edgeProperty),
                TypeInformation.of(new TypeHint<Tuple3<String, String, Integer>>() {
                }));_
 Do you have any idea why it happens?
Thanks
-Ronald

**Comment by rayokota** [comment]
Connections are reused so they should not be a problem.  Did you try turning off or configuring caching to see if it helps with memory? https://github.com/rayokota/hgraphdb#performance-tuning

**Comment by ronaldFeri** [comment]
Thanks for the answer. Well, I think that there is a problem (a sort of memory leakage), we run a cluster and when loading 13 million edges from HgraphDB it takes up to 15-20 GB memory and doesn't release the memory even after completing the job. So if you load the same data (sequentially- one after another Or at same time) five times, the whole cluster would crash (the cluster have 100 GB memory). We tested it several times even by **disabling the cache** and it didn't help. 
I dig deeper into the problem and realize there are many suspended threads even after completing the job. Here is a snapshot which shows the suspended threads:
![image](https://user-images.githubusercontent.com/34098372/39081685-d17ba286-455a-11e8-8a9e-6d32969e1222.png)
In our test, we use VisualVM tool to monitor the heap. To verify the problem, you can run Flink in your local system and upload a job which load data from HgraphDB. Then use VisualVM to monitor the memory and threads of your jobs. 

- bests
Ronald

**Comment by rayokota** [comment]
I'm not sure those threads are the cause of your memory issues, but I believe that you can control the number of threads through the `hbase.hconnection.threads.max` configuration property, which defaults to 256.

https://github.com/apache/hbase/blob/master/hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java#L419

**Comment by rayokota** [comment]
I added some additional cleanup code for the Flink use case that may help you.  Please try version 1.0.6.

**Comment by ronaldFeri** [comment]
I tries the latest version (1.0.6) and it didn't work. I put a portion of threads dump of the latest version, maybe it helps: 
```
"hconnection-0x69544795-shared--pool1-t512" #2215 daemon prio=5 os_prio=0 tid=0x00007f91a4059000 nid=0x2230 waiting on condition [0x00007f9169e2e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000008dca4010> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"hconnection-0x69544795-shared--pool1-t511" #2214 daemon prio=5 os_prio=0 tid=0x00007f91a4055000 nid=0x222f waiting on condition [0x00007f9168753000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000008dca4010> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"hconnection-0x272d8641-shared--pool1-t518" #2213 daemon prio=5 os_prio=0 tid=0x0000000001e70000 nid=0x222e waiting on condition [0x00007f916656c000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000008ca32798> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"hconnection-0x272d8641-shared--pool1-t517" #2212 daemon prio=5 os_prio=0 tid=0x0000000001e67800 nid=0x222d waiting on condition [0x00007f9175438000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000008ca32798> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None


```

**Comment by rayokota** [comment]
Ok, I added code to close all HBase connections when the HBaseGraph is closed.   Please try out 1.0.7.  If `HBaseGraph.close()` is not getting called in your use case, I'll need more info.

**Comment by ronaldFeri** [comment]
I tested the new version and disabled the cache, but it didn't work. Here is my memory usage (job was started at 2:46 and completed at 2:48):
![image](https://user-images.githubusercontent.com/34098372/39121487-07992cc8-4707-11e8-8ebc-f06a8ce948c7.png)

Here is number of threads diagram :
![image](https://user-images.githubusercontent.com/34098372/39121528-28d1835e-4707-11e8-9fa8-ab8e5d8199f4.png)

Here is threads activities time-line:  
![image](https://user-images.githubusercontent.com/34098372/39121574-4cfdb0e0-4707-11e8-972c-42578055d1ad.png)

Here is Metaspace usage: 
![image](https://user-images.githubusercontent.com/34098372/39121641-752b5838-4707-11e8-88fe-c7296e25e9a6.png)

Here is CPU usage (blue lines are garbage collection activities which are normal):
![image](https://user-images.githubusercontent.com/34098372/39121664-85719572-4707-11e8-9a94-66757e6243a9.png)

and finally here is threads dump: 

```
2018-04-23 15:04:12
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.152-b16 mixed mode):

"hconnection-0x3d214053-shared--pool3-t2240" #17654 daemon prio=5 os_prio=0 tid=0x00007f8d6419c000 nid=0x15b7 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"hconnection-0x71289e30-shared--pool2-t2148" #17653 daemon prio=5 os_prio=0 tid=0x00007f8d6c1fc800 nid=0x15b6 in Object.wait() [0x00007f8d44310000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1257)
        - locked <0x00000000ee98a100> (a org.apache.hadoop.hbase.ipc.Call)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:226)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:331)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.scan(ClientProtos.java:34094)
        at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:219)
        at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:64)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:200)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:360)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:334)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126)
        at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - <0x00000000ee96e910> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"hconnection-0x394215aa-shared--pool4-t2155" #17652 daemon prio=5 os_prio=0 tid=0x00007f8d78196000 nid=0x15b5 waiting on condition [0x00007f8d25d25000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000b68a9a90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"hconnection-0x48713b9d-shared--pool1-t2147" #17651 daemon prio=5 os_prio=0 tid=0x00007f8d74597000 nid=0x15b4 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"hconnection-0x394215aa-shared--pool4-t2154" #17650 daemon prio=5 os_prio=0 tid=0x00007f8d7818c800 nid=0x15b3 waiting on condition [0x00007f8d42bf9000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000b68a9a90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"hconnection-0x71289e30-shared--pool2-t2147" #17649 daemon prio=5 os_prio=0 tid=0x00007f8d6c3c0800 nid=0x15b2 waiting on condition [0x00007f8d1eeb7000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000009af0f0e0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"hconnection-0x3d214053-shared--pool3-t2239" #17648 daemon prio=5 os_prio=0 tid=0x00007f8d6411c800 nid=0x15b1 waiting on condition [0x00007f8d2fccb000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000b67f9d40> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"hconnection-0x4ce4843a-shared--pool1-t4316" #17647 daemon prio=5 os_prio=0 tid=0x00007f8d882e9000 nid=0x15b0 waiting on condition [0x00007f8d1a46d000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000b6782af8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"hconnection-0x4ce4843a-shared--pool1-t4315" #17646 daemon prio=5 os_prio=0 tid=0x00007f8d881d6800 nid=0x15af waiting on condition [0x00007f8d2cf9e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000b6782af8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"hconnection-0x4ce4843a-shared--pool1-t4314" #17645 daemon prio=5 os_prio=0 tid=0x00007f8d8c108800 nid=0x15ae waiting on condition [0x00007f8d2521a000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000b6782af8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None
```

**Comment by rayokota** [comment]
Can you try making an explicit call to `HBaseGraphUtils.closeConnections()` to see if it cleans up those connections for you?  https://github.com/rayokota/hgraphdb/blob/master/src/main/java/io/hgraphdb/HBaseGraphUtils.java#L74

**Comment by ronaldFeri** [comment]
It returns this error:

```
java.lang.RuntimeException: java.util.concurrent.RejectedExecutionException: Task org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture@1d237d97 rejected from java.util.concurrent.ThreadPoolExecutor@41c6087c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 49]
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:227)
	at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:277)
	at org.apache.hadoop.hbase.client.ClientScanner.loadCache(ClientScanner.java:438)
	at org.apache.hadoop.hbase.client.ClientScanner.next(ClientScanner.java:312)
	at org.apache.flink.addons.hbase.AbstractTableInputFormat.nextRecord(AbstractTableInputFormat.java:139)
	at org.apache.flink.runtime.operators.DataSourceTask.invoke(DataSourceTask.java:167)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:702)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.RejectedExecutionException: Task org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture@1d237d97 rejected from java.util.concurrent.ThreadPoolExecutor@41c6087c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 49]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at org.apache.hadoop.hbase.client.ResultBoundedCompletionService.submit(ResultBoundedCompletionService.java:171)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.addCallsForCurrentReplica(ScannerCallableWithReplicas.java:321)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:182)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:58)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:219)
	... 7 more

```

**Comment by rayokota** [comment]
Ok, so resources aren't getting cleaned up because Flink is still running.  I believe you can stop your Flink jobs using the command line.  If that doesn't work, you should probably try the Flink mailing list.
