### ISSUE TITLE
Hbase 2.0+ Support

### ISSUE THREAD

**Issue by jgunzelman88** [rayokota/hgraphdb#62]
Do you have any plans to support hbase 2.0+?  I am using CDH 6.2 and I am getting a error when trying to create a table. 

java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class io.hgraphdb.HBaseGraph]

Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78)
	... 36 more
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.hbase.client.Admin.createTable(Lorg/apache/hadoop/hbase/HTableDescriptor;)V
	at io.hgraphdb.HBaseGraphUtils.createTable(HBaseGraphUtils.java:147)
	at io.hgraphdb.HBaseGraphUtils.createTables(HBaseGraphUtils.java:118)
	at io.hgraphdb.HBaseGraphUtils.createTables(HBaseGraphUtils.java:102)
	at io.hgraphdb.HBaseGraph.<init>(HBaseGraph.java:138)
	at io.hgraphdb.HBaseGraph.<init>(HBaseGraph.java:128)
	at io.hgraphdb.HBaseGraph.<init>(HBaseGraph.java:107)
	at io.hgraphdb.HBaseGraph.open(HBaseGraph.java:95)
	... 41 more

**Comment by rayokota** [comment]
Yes, it's on my todo list

**Comment by jgunzelman88** [comment]
I know this is asking a lot but do you have a rough time frame?  Just want to know if I need to go down the janus graph route or not

**Comment by shu19900209** [comment]
I using CDH6.1.1，clone the project,  modify the dependencies, modify the code a little bit, repackage. It works well. @jgunzelman88
